### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *Missing php-string and php-xml*
- *Don't follow example template*

## Solution
- *Adding missing dependencies*
- *Normalize*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/ttrss_ynh%20PR66/)
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by Josue-T** [comment]
Tried this testing version now it fail with this error:
```
153023 DEBUG ++ echo ''
153024 DEBUG ++ tr '\n' +
153025 DEBUG + local weight_values=26
153026 DEBUG + local max_progression=31
153028 DEBUG + increment_progression=14
153029 DEBUG + previous_weight=2
153030 DEBUG + local scale=20
153032 DEBUG + local progress_string1=####################
153033 DEBUG + local progress_string0=....................
153034 DEBUG + '[' 0 -eq 0 ']'
153035 DEBUG + local effective_progression=9
153036 DEBUG + local progression_bar=#########...........
153038 DEBUG + local print_exec_time=
153039 DEBUG + '[' 0 -eq 1 ']'
153040 DEBUG + ynh_print_info '[#########...........] > Reconfiguring ttrss...'
153042 DEBUG + local legacy_args=m
153043 DEBUG + args_array=([m]=message=)
153052 WARNING ./upgrade: ligne 131: tmpdir : variable sans liaison
153055 DEBUG + declare -Ar args_array
153059 WARNING !!
153062 DEBUG + local message
153064 WARNING   ttrss's script has encountered an error. Its execution was cancelled.
153066 INFO [#########...........] > Reconfiguring ttrss...
153067 DEBUG + ynh_handle_getopts_args '[#########...........] > Reconfiguring ttrss...'
153069 WARNING !!
153070 DEBUG + set +x
153071 WARNING Upgrade failed.
```

**Comment by maniackcrudelis** [comment]
We indeed do not test that case with an upgrade of the package only.
$tmpdir was declared only for core upgrade.

But there's actually no reason to reconfigure the app if there's no upgrade of the core.

**Comment by Josue-T** [comment]
> We indeed do not test that case with an upgrade of the package only.
$tmpdir was declared only for core upgrade.

> But there's actually no reason to reconfigure the app if there's no upgrade of the core.

Work this time, thanks

**Comment by kay0u** [comment]
Bump

**Comment by maniackcrudelis** [comment]
May 13...
LGTM...

**Comment by maniackcrudelis** [comment]
Let's merge in 3 days.

**Pull request merged**
