### PR TITLE
Service was added during install, but not remove during remove...

### PR DESCRIPTION
**Pull request by alexAubin**
## Problem

Service is added during install, but not removed during remove ... This causes this kind of issue : https://forum.yunohost.org/t/fetchfailedexception/6945

## Solution

Remove teh service bruh

## PR Status

Not tested ... random commit while passing by.

- [X] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Josué
- [x] **Approval (LGTM)** : Josué
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/ttrss_ynh%20PR56%20(Official_fork)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by alexAubin** [comment]
Meh I messed up the branches, not sure why :|

**Comment by maniackcrudelis** [comment]
For reviewing, consider only the remove script: https://github.com/YunoHost-Apps/ttrss_ynh/pull/56/files#diff-5eed0b3fcd28fe6d787e5405728a2ca8

**Comment by JimboJoe** [comment]
I guess we can merge in 3 days...?

**Comment by alexAubin** [comment]
ˢᵐᵒˡ ᵇᵘᵐᵖ

**Pull request merged**
