### PR TITLE
Add missing php-string and php-xml dependencies

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Some dependencies are missing (reported in the support chat room)*

## Solution
- *Add these dependencies*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/ttrss_ynh%20fix_add_dependencies%20(Official)/)
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
I recommend to wait for the current testing #59 to be released before merging :sweat_smile:

**Comment by JimboJoe** [comment]
Testing has been released, this can be reviewed

**Comment by maniackcrudelis** [comment]
As you add php-mbstring and php-xml as dependencies, I guess those dependencies are used by ttrss itself, not only the install script.
In that case, it should probably be as well in upgrade and restore script.

**Comment by maniackcrudelis** [comment]
Looks ok to me.
I'd like to see what the CI will say.

**Comment by kay0u** [comment]
Will be merged in 3 days

**Comment by JimboJoe** [comment]
Will be merged in 3 days.

**Pull request merged**
